name: Update

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(TZ=UTC date +'%Y-%m-%d-%H-%M-UTC')"

      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2

      - name: Fetch API Data
        run: python ./scripts/fetch.py
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      
      - name: Commit and Push
        run: |
          git config user.name "aoisensi"
          git config user.email "me@aoisensi.info"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated ${{ steps.date.outputs.date }}"
          git push origin master
